
dist: xenial
sudo: false

language: scala
scala:
- 2.12.8
jdk:
- openjdk8

addons:
#  chrome: stable
  apt:
    packages:
        # this installs matching chrome browser
      - chromium-chromedriver
  snaps:
    - hugo

branches:
  only: 
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

#before_install:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start

install: # Install ChromeDriver
  - npm config set ignore-scripts true
  
before_script:
  - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver
  
script:
# - export ParallelUtilsUseSerial=false
- export UseBrowser=chromeheadless
- export UseFullOpt=true
- sbt clean distribution:travis

after_failure:
- cat server/logs/unittestTcpMonitorTimeWait.csv
# - cat server/logs/unittest.1.log

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KZFkOMFKXuabrzdsh7O5B5Sq9m2Ymf4M7YLSFFFClWK2s0EhMabAbsKJqylXCqYB+Hhi1nZDv6IHH0QZvuVd2HhlPUJt6/eAsI8/9FvmDKFZQlybEFeg66ogd7N1OAr8IbFAh/bXW1k9t7YwhTQOL6VoOSrm37jrQPshrVfwgw8bgdoWiMO0oTPcpsSN5qNqlLooz0fwpA2gk49KC1ZnLrq2S4F8KOIAAnkMWYdb9hTJRBlkQqIV/r6O65IZT9ZvVxqJNYBnpPUsL558D57AcWiya0QFWPGvz2cO1GcekzYyG7T110HjyiSnJSHciSOlXjro7AS+C9iwo/T9FHmtULB0WIgnyEZrBEc/GyqIZX7PAiBeXXcPhe/ac1IHbnwiomiVcTgOqr8Fc2b3YVNqX+hQKIdWa4+LYeVoVibeusUnqM91Eun6U26ljNLucJ8e1pVuAg5kZw3DWbpX37qDeSL85Epk1JgikijvjWpBt+P+STldsvb/zadPzAfmyEJW5auHgQ4YMniaGIwUd58aQa/wH5ZLPW1wt1ONgTgs/B21Os5FSXRxpf7ZAbX9hvFEdQhHos7/4TeKw1+0z/4F8nKtFocxcg3VRjQ9OGgTCM6LhF1DhQYQcMq+Y7rMcMqpegfGrCbE2v1eYpJWJGMuL0Gxhi0RFUrhPMUtFmU5lak=
  file_glob: true
  file:
    - target/scala-2.12/bridgescorer-server-assembly-*.jar
    - target/scala-2.12/bridgescorer-server-assembly-*.jar.sha256
  on:
    repo: thebridsk/bridgescorer
    tags: true
