
os: linux
dist: xenial

language: scala
scala:
- 2.12.10
jdk:
- openjdk8

env:
  - NODE_VERSION="12.13.1"

#addons:
##  chrome: stable
#  apt:
#    packages:
#        # this installs matching chrome browser
#      - chromium-chromedriver
#  snaps:
#    - hugo

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

#before_install:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start

install: # Install ChromeDriver
  - npm config set ignore-scripts true

#before_script:
#  - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

#script:
## - export ParallelUtilsUseSerial=false
#- export UseBrowser=chromeheadless
#- export UseFullOpt=true
#- sbt clean distribution:travis

jobs:
  include:
    - stage: test
      before_install:
        - nvm install $NODE_VERSION
      script:
        - |
          cat /proc/meminfo
          which sbt
          cat /etc/sbt/jvmopts
          node --version
          npm --version
          # export JVM_OPTS=@travis/jvmopts.txt
          # cat travis/jvmopts.txt
          export ServerTestToRun=com.github.thebridsk.bridge.fullserver.test.AllUnitTests
          export UseFullOpt=true
          travis/cmdWithPeriodicMsg.sh sbt setOptimize distribution:travis1
    - stage: systemtest
      addons:
      #  chrome: stable
        apt:
          packages:
            # this installs matching chrome browser
            - chromium-chromedriver
        snaps:
          - name: hugo
      before_install:
        - nvm install $NODE_VERSION
      before_script:
        - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver
      script:
        - |
          cat /proc/meminfo
          which sbt
          cat /etc/sbt/jvmopts
          # export JVM_OPTS=@travis/jvmopts.txt
          # cat travis/jvmopts.txt
          chromedriver --version
          which google-chrome
          google-chrome --version
          which chromium-browser
          chromium-browser --version
          sudo mv -f /usr/bin/chromium-browser /usr/bin/google-chrome
          export UseBrowser=chromeheadless
          export UseFullOpt=true
          export ServerTestToRun=com.github.thebridsk.bridge.fullserver.test.selenium.AllSeleniumSuites
          travis/cmdWithPeriodicMsg.sh sbt setOptimize distribution:travis2

after_failure:
- cat server/logs/unittestTcpMonitorTimeWait.csv
# - cat server/logs/unittest.1.log

deploy:
- provider: releases
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  file_glob: true
  file:
    - bridgescorekeeper/target/scala-2.13/bridgescorekeeper-server-*.jar
    - bridgescorekeeper/target/scala-2.13/bridgescorekeeper-server-*.jar.sha256
  on:
    repo: thebridsk/bridgescorer
    tags: true

- provider: pages
  repo:  thebridsk/bridgescorerdemo
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  target_branch: gh-pages
  local_dir: demo/target/demo
  strategy: git
  on:
    repo: thebridsk/bridgescorer
    tags: true
