#!/bin/bash

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

helpme()
{
  cat <<HELPMEHELPME
Syntax: $0 [-h|--help]

Collects the diagnostic information and saves it in logs.zip.
Java 8 must be on the path.
  
HELPMEHELPME
}

if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
  helpme
  exit 1
fi

cd $SCRIPTDIR

jarcount=`ls -1f bridgescorer-server-assembly-*.jar bridgescorekeeper-*.jar 2>/dev/null | wc -l`
if [[ $jarcount -ne "1" ]] ; then 
  echo Did not find one bridgescorer jar file in directory, found $jarcount
  ls bridgescorer-server-assembly-*.jar bridgescorekeeper-*.jar 2>/dev/null
  exit 1
fi

oldjar=`ls -1f bridgescorer-server-assembly-*.jar bridgescorekeeper-*.jar 2>/dev/null`

java -jar $oldjar collectlogs --store ./store --diagnostics ./logs --zip logs.zip

