#!/bin/bash

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

helpme()
{
  cat <<HELPMEHELPME
Syntax: $0 [-h|--help]

Starts the bridge scorer server.  Java 8 must be on the path.
  
HELPMEHELPME
}

if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
  helpme
  exit 1
fi

cd $SCRIPTDIR

java -jar bridgescorer-server-assembly-*.jar collectlogs --store ./store --zip logs.zip

