#!/bin/bash

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

helpme()
{
  cat <<HELPMEHELPME
Syntax: $0 [-h|--help]

Starts the bridge scorer server.  Java 8 must be on the path.
  
HELPMEHELPME
}

if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
  helpme
  exit 1
fi

cd $SCRIPTDIR

jarcount=`ls -1f bridgescorer-server-assembly-*.jar bridgescorekeeper-*.jar 2>/dev/null | wc -l`
if [[ $jarcount -ne "1" ]] ; then 
  echo Did not find one bridgescorer jar file in directory, found $jarcount
  ls bridgescorer-server-assembly-*.jar bridgescorekeeper-*.jar 2>/dev/null
  exit 1
fi

oldjar=`ls -1f bridgescorer-server-assembly-*.jar bridgescorekeeper-*.jar 2>/dev/null`

mkdir logs 2>/dev/null
java -jar $oldjar --logfile logs/server.%d.%u.log --memoryfile logs/memory.%%d.csv start --store ./store --port 8080 --browser --diagnostics logs

