#!/bin/zsh

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

helpme()
{
  cat <<HELPMEHELPME
Syntax: $0 [-h|--help]

Starts the bridge scorer server.  Java 8 must be on the path.

HELPMEHELPME
}

if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
  helpme
  exit 1
fi

cd $SCRIPTDIR

# looking for jar files with the following file name patterns:
#   bridgescorer-server-assembly-*.jar
#   bridgescorekeeper-*.jar
jarcount=`ls -1f *.jar 2>/dev/null | wc -l`
if [[ $jarcount -ne "1" ]] ; then
  echo Did not find one bridgescorer jar file in directory, found $jarcount
  ls *.jar 2>/dev/null
  exit 1
fi

oldjar=`ls -1f *.jar 2>/dev/null`

java -jar $oldjar update
if [[ $? -ne 0 ]] ; then
  echo Update not done
  exit 1
fi

jarcount2=`ls -1f *.jar 2>/dev/null | wc -l`
if [[ $jarcount2 -ne "2" ]] ; then
  echo jar count is $jarcount2
  echo Should find both old and new bridgescorer jar file in directory, found $jarcount2
  ls *.jar 2>/dev/null
  exit 1
fi

files=(`ls -1f *.jar 2>/dev/null`)

determineNewJar() {
  if [[ "$1" == "$oldjar" ]] ; then
    newjar=$2
  else
    newjar=$1
  fi
}

determineNewJar ${files}

echo New bridgescorer jar file is $newjar

java -jar $newjar install

mkdir save 2>/dev/null
mv $oldjar save/
mv ${oldjar}.sha256 save/
